development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://184.72.235.111:9292/faye"
  secret_token: "75a7485aeed08961e249a3db5e03fb6f60364eec013d99a8e0d9f457b661f8c9"
  signature_expiration: 3600 # one hour
staging:
  server: "http://184.72.235.111:9292/faye"
  secret_token: "75a7485aeed08961e249a3db5e03fb6f60364eec013d99a8e0d9f457b661f8c9"
  signature_expiration: 3600 # one hour
production:
  server: "http://184.72.235.111:9292/faye"
  secret_token: "75a7485aeed08961e249a3db5e03fb6f60364eec013d99a8e0d9f457b661f8c9"
  signature_expiration: 3600 # one hour
